version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: registry-front
    restart: always
    ports:
      - 17000:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/keys:/keys
